import type { ChapterConfig, LevelConfig } from './types';

export const tutorialLevel: LevelConfig = {
  id: 0,
  chapterId: 1,
  title: 'Tutorial: Cluster Boot & Basics',
  subtitle: 'Academy Simulation • Guided Introduction',
  description: 'Learn the core Kubernetes defense mechanics: inspect worker nodes, deploy pods via kubectl, observe the lifecycle, and power up worker node defenses.',
  initialNodes: [
    {
      name: 'worker-1',
      role: 'worker',
      status: 'Ready',
      health: 100,
      cpuCapacity: 2.0,
      memoryCapacity: 4096, // 4Gi
      cpuAllocatable: 1.8,
      memoryAllocatable: 3584,
      cpuRequested: 0,
      memoryRequested: 0,
      pods: [],
      laneIndex: 0,
      labels: { 'node-role.kubernetes.io/worker': '', 'topology.kubernetes.io/zone': 'lane-1' },
      turretAngle: 0,
      serviceCapacity: 0,
    },
    {
      name: 'worker-2',
      role: 'worker',
      status: 'Ready',
      health: 100,
      cpuCapacity: 4.0,
      memoryCapacity: 8192, // 8Gi
      cpuAllocatable: 3.8,
      memoryAllocatable: 7680,
      cpuRequested: 0,
      memoryRequested: 0,
      pods: [],
      laneIndex: 1,
      labels: { 'node-role.kubernetes.io/worker': '', 'topology.kubernetes.io/zone': 'lane-2' },
      turretAngle: 0,
      serviceCapacity: 0,
    },
    {
      name: 'worker-3',
      role: 'worker',
      status: 'Ready',
      health: 100,
      cpuCapacity: 2.0,
      memoryCapacity: 2048, // 2Gi
      cpuAllocatable: 1.8,
      memoryAllocatable: 1792,
      cpuRequested: 0,
      memoryRequested: 0,
      pods: [],
      laneIndex: 2,
      labels: { 'node-role.kubernetes.io/worker': '', 'topology.kubernetes.io/zone': 'lane-3' },
      turretAngle: 0,
      serviceCapacity: 0,
    },
  ],
  requests: [
    {
      id: 'tut-001',
      customerName: 'Training AI Supervisor',
      customerRole: 'Kubernetes Flight Instructor',
      characterType: 'normal',
      title: 'Academy Drill 1: Inspect Worker Nodes',
      description: 'Welcome Cadet! First, verify the status of our cluster worker nodes using the standard Kubernetes CLI.',
      requirements: {
        type: 'inspect-nodes',
        kind: 'COMMAND',
      },
      lane: 0,
      slaTimeSeconds: 120,
      rewardPoints: 100,
      hints: [
        'You need to list the nodes in the Kubernetes cluster.',
        "The 'kubectl get' command is used to list Kubernetes resources.",
        "Add the resource type 'nodes' or 'node' to the command.",
        'Execute: kubectl get nodes',
      ],
      learningNote: 'All 3 worker nodes (worker-1, worker-2, worker-3) are in Ready state with allocatable CPU and Memory ready for scheduling.',
    },
    {
      id: 'tut-002',
      customerName: 'Cadet Support System',
      customerRole: 'Automated Workload Generator',
      characterType: 'normal',
      title: 'Academy Drill 2: Deploy NGINX Web Pod',
      description: 'Incoming customer request detected! Deploy an nginx pod named web-01. Notice the lifecycle: Pending -> Scheduled -> ContainerCreating -> Running -> Ready!',
      requirements: {
        type: 'create-pod',
        kind: 'STATE',
        podName: 'web-01',
        image: 'nginx',
        requireReady: true,
      },
      lane: 1,
      slaTimeSeconds: 90,
      rewardPoints: 150,
      hints: [
        'You need to create a simple Pod workload.',
        "The 'kubectl run' command creates a Pod in the API server.",
        'Provide the pod name (web-01) and container image (--image=nginx).',
        'Execute: kubectl run web-01 --image=nginx',
      ],
      learningNote: 'Creating the Pod object in etcd is only step 1. The scheduler selects a node, kubelet starts the container, and once Ready, the workload serves traffic!',
    },
  ],
  learningOutcomes: [
    'Worker nodes provide compute capacity (Allocatable CPU/RAM) to run container workloads.',
    'Kubernetes objects are managed through the bastion terminal using "kubectl".',
    'The Kube-Scheduler automatically assigns pending pods to nodes based on resource availability.',
    'A successful command creates the API object, but the workload serves traffic only when Running & Ready.',
  ],
};

export const chapter01Levels: LevelConfig[] = [
  {
    id: 1,
    chapterId: 1,
    title: 'Level 1: Nodes & Pod Placement',
    subtitle: 'Cluster Architecture, Allocatable Capacity & Lifecycle',
    description: 'Learn how Kubernetes worker nodes run container workloads, how kube-scheduler assigns Pods, and how resource requests affect scheduling.',
    initialNodes: [
      {
        name: 'worker-1',
        role: 'worker',
        status: 'Ready',
        health: 100,
        cpuCapacity: 2.0,
        memoryCapacity: 4096, // 4Gi
        cpuAllocatable: 1.8,
        memoryAllocatable: 3584,
        cpuRequested: 0,
        memoryRequested: 0,
        pods: [],
        laneIndex: 0,
        labels: { 'node-role.kubernetes.io/worker': '', 'topology.kubernetes.io/zone': 'lane-1' },
        turretAngle: 0,
        serviceCapacity: 0,
      },
      {
        name: 'worker-2',
        role: 'worker',
        status: 'Ready',
        health: 100,
        cpuCapacity: 4.0,
        memoryCapacity: 8192, // 8Gi
        cpuAllocatable: 3.8,
        memoryAllocatable: 7680,
        cpuRequested: 0,
        memoryRequested: 0,
        pods: [],
        laneIndex: 1,
        labels: { 'node-role.kubernetes.io/worker': '', 'topology.kubernetes.io/zone': 'lane-2' },
        turretAngle: 0,
        serviceCapacity: 0,
      },
      {
        name: 'worker-3',
        role: 'worker',
        status: 'Ready',
        health: 100,
        cpuCapacity: 2.0,
        memoryCapacity: 2048, // 2Gi
        cpuAllocatable: 1.8,
        memoryAllocatable: 1792,
        cpuRequested: 0,
        memoryRequested: 0,
        pods: [],
        laneIndex: 2,
        labels: { 'node-role.kubernetes.io/worker': '', 'topology.kubernetes.io/zone': 'lane-3' },
        turretAngle: 0,
        serviceCapacity: 0,
      },
    ],
    requests: [
      {
        id: 'req-001',
        customerName: 'Sarah Jenkins',
        customerRole: 'Cluster Architect',
        characterType: 'normal',
        title: '1A: Inspect Cluster Nodes',
        description: 'Welcome to the Bastion terminal! First, inspect the cluster to verify all worker nodes are in Ready status.',
        requirements: {
          type: 'inspect-nodes',
          kind: 'COMMAND',
        },
        lane: 0,
        slaTimeSeconds: 90,
        rewardPoints: 100,
        hints: [
          'You need to list the nodes in the Kubernetes cluster.',
          "The 'kubectl get' command is used to list Kubernetes resources.",
          "Add the resource type 'nodes' or 'node' to the command.",
          'Execute: kubectl get nodes',
        ],
        learningNote: 'The cluster has 3 worker nodes (worker-1, worker-2, worker-3) in Ready state.',
      },
      {
        id: 'req-002',
        customerName: 'Mike Chen',
        customerRole: 'Frontend Lead',
        characterType: 'normal',
        title: '1B: Deploy First NGINX Workload',
        description: 'Customer requests a web frontend! Create an nginx pod named web-01. Notice how API object creation is followed by scheduling and container startup before it becomes Ready.',
        requirements: {
          type: 'create-pod',
          kind: 'STATE',
          podName: 'web-01',
          image: 'nginx',
          requireReady: true,
        },
        lane: 1,
        slaTimeSeconds: 70,
        rewardPoints: 150,
        hints: [
          'You need to create a simple Pod workload.',
          "The 'kubectl run' command creates a Pod object in the API server.",
          'Provide the pod name (web-01) and container image (--image=nginx).',
          'Execute: kubectl run web-01 --image=nginx',
        ],
        learningNote: 'The API server accepts the object, kube-scheduler binds it to an eligible node, and kubelet starts the container. When Ready, the customer request is served!',
      },
      {
        id: 'req-003',
        customerName: 'Elena Rostova',
        customerRole: 'SRE Specialist',
        characterType: 'normal',
        title: '1C: Discover Pod Placement (-o wide)',
        description: 'Find out which worker node the Kubernetes scheduler selected for web-01 using extended output columns.',
        requirements: {
          type: 'inspect-pods-wide',
          kind: 'OBSERVATION',
        },
        lane: 1,
        slaTimeSeconds: 70,
        rewardPoints: 120,
        hints: [
          'Regular kubectl get pods only shows basic status without the node column.',
          "Use the '-o wide' flag to display extended columns including NODE and IP.",
          'Combine kubectl get pods with the wide output format option.',
          'Execute: kubectl get pods -o wide',
        ],
        learningNote: "The '-o wide' flag reveals the NODE column. The scheduler evaluated candidate nodes and placed web-01 on the best scoring worker node.",
      },
      {
        id: 'req-004',
        customerName: 'Marcus Wright',
        customerRole: 'Platform Engineer',
        characterType: 'normal',
        title: '1D: Inspect Node Capacity & Allocatable',
        description: 'Inspect a worker node to observe Capacity vs Allocatable CPU/Memory and non-terminated pods running on it.',
        requirements: {
          type: 'describe-node',
          kind: 'OBSERVATION',
        },
        lane: 0,
        slaTimeSeconds: 65,
        rewardPoints: 140,
        hints: [
          "The 'describe' command shows detailed resource allocations and events for an object.",
          "Specify the resource type 'node' and any worker name (e.g. worker-1, worker-2, or worker-3).",
          'Syntax: kubectl describe node <node-name>',
          'Execute: kubectl describe node worker-2',
        ],
        learningNote: 'Capacity is total physical compute. Allocatable is what remains for workloads after system reservations. The scheduler evaluates Allocatable free capacity.',
      },
      {
        id: 'req-005',
        customerName: 'Klaus Mueller',
        customerRole: 'ML Infrastructure',
        characterType: 'cpu-burner',
        title: '1E: Declarative Workload with CPU Request (500m)',
        description: 'Customer requests a dedicated compute pod! Apply the declarative YAML manifest compute-01.yaml (specifying 500m CPU request).',
        requirements: {
          type: 'create-pod',
          kind: 'STATE',
          podName: 'compute-01',
          image: 'nginx',
          minCpu: 0.5,
          requireReady: true,
          manifestFile: 'compute-01.yaml',
        },
        lane: 2,
        slaTimeSeconds: 60,
        rewardPoints: 200,
        hints: [
          'In production Kubernetes, workloads are deployed declaratively using YAML manifests.',
          "Use 'ls' to see manifests, or 'cat compute-01.yaml' to inspect its contents.",
          "Apply the manifest with 'kubectl apply -f compute-01.yaml'.",
          'Execute: kubectl apply -f compute-01.yaml',
        ],
        learningNote: 'The scheduler uses CPU requests (500m = 0.5 cores) when checking if the Pod fits within Node allocatable capacity.',
      },
      {
        id: 'req-006',
        customerName: 'Ananya Roy',
        customerRole: 'Database Administrator',
        characterType: 'memory-hog',
        title: '1E: Declarative Memory Cache (1024Mi RAM)',
        description: 'High-RAM workload incoming! Apply db-01.yaml to deploy a Redis cache requesting 1024Mi memory.',
        requirements: {
          type: 'create-pod',
          kind: 'STATE',
          podName: 'db-01',
          image: 'redis',
          minMem: 1024,
          requireReady: true,
          manifestFile: 'db-01.yaml',
        },
        lane: 0,
        slaTimeSeconds: 55,
        rewardPoints: 220,
        hints: [
          'Deploy the database cache using its declarative manifest.',
          "Use 'kubectl apply -f db-01.yaml' to deploy.",
          'View the file first with: cat db-01.yaml',
          'Execute: kubectl apply -f db-01.yaml',
        ],
        learningNote: 'Memory requests tell the scheduler how much RAM the workload expects and are used during the node filtering and scoring phases.',
      },
      {
        id: 'req-007',
        customerName: 'Devon Vance',
        customerRole: 'Chaos Engineering Lead',
        characterType: 'escalation',
        title: '1F: Failed Scheduling & Diagnosis',
        description: 'A developer applied big-cache.yaml requesting 16Gi RAM (more than any node has allocatable). Apply it and observe why it remains in Pending status!',
        requirements: {
          type: 'failed-scheduling',
          kind: 'STATE',
          podName: 'big-cache',
        },
        lane: 1,
        slaTimeSeconds: 60,
        rewardPoints: 250,
        hints: [
          'Apply the oversized manifest: kubectl apply -f big-cache.yaml.',
          'Notice that the command succeeds (API object created), but the pod status remains Pending.',
          'Inspect why the scheduler failed to place it using: kubectl describe pod big-cache',
          'Execute: kubectl apply -f big-cache.yaml',
        ],
        learningNote: 'When no node has enough allocatable resources, the Pod remains Pending with a FailedScheduling warning event. Describing the pod reveals the exact root cause!',
      },
      {
        id: 'req-008',
        customerName: 'Devon Vance',
        customerRole: 'Chaos Engineering Lead',
        characterType: 'normal',
        title: '1F: Cleanup Unschedulable Workload',
        description: 'Clean up the unschedulable big-cache pod to keep the cluster namespace healthy.',
        requirements: {
          type: 'delete-pod',
          kind: 'STATE',
          podName: 'big-cache',
        },
        lane: 1,
        slaTimeSeconds: 50,
        rewardPoints: 150,
        hints: [
          'You need to clean up the unschedulable workload object.',
          "Delete the pending pod using 'kubectl delete pod <name>'.",
          'Target pod is big-cache.',
          'Execute: kubectl delete pod big-cache',
        ],
        learningNote: 'Deleting the pod removes the object from etcd and frees any queue slots for other pending workloads.',
      },
      {
        id: 'req-009',
        customerName: 'VP of Engineering',
        customerRole: 'Executive Incident Commander',
        characterType: 'urgent',
        title: '1F: Enterprise Gateway Deployment',
        description: 'Production traffic surge! Deploy the enterprise gateway using gateway-01.yaml (1000m CPU, 2048Mi RAM).',
        requirements: {
          type: 'create-pod',
          kind: 'STATE',
          podName: 'gateway-01',
          image: 'nginx',
          minCpu: 1.0,
          minMem: 2048,
          requireReady: true,
          manifestFile: 'gateway-01.yaml',
        },
        lane: 2,
        slaTimeSeconds: 50,
        rewardPoints: 350,
        hints: [
          'Deploy the gateway workload with: kubectl apply -f gateway-01.yaml',
          'The scheduler evaluates remaining allocatable capacity on all 3 nodes.',
          'Only worker-2 has sufficient remaining allocatable resources (3.8 CPU, 7.5Gi RAM).',
          'Execute: kubectl apply -f gateway-01.yaml',
        ],
        learningNote: 'The Kube-Scheduler evaluated all candidate nodes against remaining allocatable capacity and successfully bound gateway-01!',
      },
    ],
    learningOutcomes: [
      'Worker nodes provide compute capacity (Allocatable CPU/RAM) for container workloads.',
      'Pods are the fundamental unit of deployment in Kubernetes.',
      'The Kube-Scheduler filters nodes based on Allocatable capacity, taints, and status, then scores eligible nodes.',
      'A successful CLI command creates the API object in etcd, but workloads only serve traffic when Running and Ready.',
      'kubectl describe node and kubectl describe pod provide vital observability into resource allocations and lifecycle events.',
      'When resource requests exceed node allocatable capacity, the Pod remains Pending with a FailedScheduling event.',
    ],
  },
];

export const allChapters: ChapterConfig[] = [
  {
    id: 1,
    title: 'Chapter 1: Nodes & Scheduling',
    description: 'Learn cluster anatomy, allocatable capacity, pod placement, and kube-scheduler scoring.',
    badge: 'NODES',
    unlocked: true,
    levels: chapter01Levels,
  },
  {
    id: 2,
    title: 'Chapter 2: Pods & Lifecycle',
    description: 'Master Pod lifecycle states: Pending, ContainerCreating, Running, CrashLoopBackOff, and ImagePullBackOff.',
    badge: 'PODS',
    unlocked: false,
    levels: [],
  },
  {
    id: 3,
    title: 'Chapter 3: Deployments & ReplicaSets',
    description: 'Master self-healing workloads, controller reconciliation, rolling updates, rollbacks, and replica scaling.',
    badge: 'DEPLOY',
    unlocked: false,
    levels: [],
  },
  {
    id: 4,
    title: 'Chapter 4: Services & Networking',
    description: 'ClusterIP, NodePort, LoadBalancer, Service selectors, and Endpoint routing.',
    badge: 'NETWORKING',
    unlocked: false,
    levels: [],
  },
  {
    id: 5,
    title: 'Chapter 5: Troubleshooting & Incidents',
    description: 'Node NotReady emergencies, OOMKilled vs Eviction, CPU throttling, and etcd quorum preservation.',
    badge: 'INCIDENTS',
    unlocked: false,
    levels: [],
  },
];
