import type { ChapterConfig, LevelConfig } from './types';

export const tutorialLevel: LevelConfig = {
  id: 0,
  chapterId: 1,
  title: 'Tutorial: Cluster Boot & Basics',
  subtitle: 'Academy Simulation • Guided Introduction',
  description: 'Learn the core Kubernetes defense mechanics: inspect worker nodes, deploy pods via kubectl, and power up worker node cannons.',
  initialNodes: [
    {
      name: 'worker-1',
      role: 'worker',
      status: 'Ready',
      health: 100,
      cpuCapacity: 2,
      memoryCapacity: 4096, // 4Gi
      cpuAllocated: 0,
      memoryAllocated: 0,
      pods: [],
      laneIndex: 0,
      labels: { 'node-role.kubernetes.io/worker': '', 'topology.kubernetes.io/zone': 'lane-1' },
      turretAngle: 0,
      ammoCount: 0,
    },
    {
      name: 'worker-2',
      role: 'worker',
      status: 'Ready',
      health: 100,
      cpuCapacity: 4,
      memoryCapacity: 8192, // 8Gi
      cpuAllocated: 0,
      memoryAllocated: 0,
      pods: [],
      laneIndex: 1,
      labels: { 'node-role.kubernetes.io/worker': '', 'topology.kubernetes.io/zone': 'lane-2' },
      turretAngle: 0,
      ammoCount: 0,
    },
    {
      name: 'worker-3',
      role: 'worker',
      status: 'Ready',
      health: 100,
      cpuCapacity: 2,
      memoryCapacity: 2048, // 2Gi
      cpuAllocated: 0,
      memoryAllocated: 0,
      pods: [],
      laneIndex: 2,
      labels: { 'node-role.kubernetes.io/worker': '', 'topology.kubernetes.io/zone': 'lane-3' },
      turretAngle: 0,
      ammoCount: 0,
    },
  ],
  requests: [
    {
      id: 'tut-001',
      customerName: 'Training AI Supervisor',
      customerRole: 'Kubernetes Flight Instructor',
      characterType: 'normal',
      title: 'Academy Drill 1: Inspect Worker Nodes',
      description: 'Welcome Cadet! First, verify the status of our cluster worker nodes using the standard Kubernetes CLI.',
      requirements: {
        type: 'inspect-nodes',
      },
      lane: 0,
      slaTimeSeconds: 120,
      rewardPoints: 100,
      hints: [
        'You need to list the nodes in the Kubernetes cluster.',
        "The 'kubectl get' command is used to list Kubernetes resources.",
        "Add the resource type 'nodes' or 'node' to the command.",
        'Execute: kubectl get nodes',
      ],
      learningNote: 'All 3 worker nodes (worker-1, worker-2, worker-3) are in Ready state with available CPU and Memory.',
    },
    {
      id: 'tut-002',
      customerName: 'Cadet Support System',
      customerRole: 'Automated Workload Generator',
      characterType: 'normal',
      title: 'Academy Drill 2: Deploy NGINX Web Pod',
      description: 'Incoming customer request detected! Deploy an nginx pod named web-01 to satisfy traffic and power up the worker cannon.',
      requirements: {
        type: 'create-pod',
        podName: 'web-01',
        image: 'nginx',
      },
      lane: 1,
      slaTimeSeconds: 90,
      rewardPoints: 150,
      hints: [
        'You need to create a simple Pod workload.',
        "The 'kubectl run' command creates and runs a container image in a Pod.",
        'Provide the pod name (web-01) and container image (--image=nginx).',
        'Execute: kubectl run web-01 --image=nginx',
      ],
      learningNote: 'When web-01 reached Running status, the assigned worker node cannon loaded ammunition and neutralized the incoming load!',
    },
  ],
  learningOutcomes: [
    'Worker nodes provide compute capacity (CPU/RAM) to run container workloads.',
    'Kubernetes objects are managed through the bastion terminal using "kubectl".',
    'The Kube-Scheduler automatically assigns pods to nodes based on resource availability.',
    'Running pods charge worker node defense cannons to resolve incoming customer requests.',
  ],
};

export const chapter01Levels: LevelConfig[] = [
  {
    id: 1,
    chapterId: 1,
    title: 'Level 1: Meet the Workers',
    subtitle: 'Cluster Architecture, Nodes & Pod Placement',
    description: 'Learn how Kubernetes worker nodes run container workloads and how the Kube-Scheduler assigns Pods.',
    initialNodes: [
      {
        name: 'worker-1',
        role: 'worker',
        status: 'Ready',
        health: 100,
        cpuCapacity: 2,
        memoryCapacity: 4096, // 4Gi
        cpuAllocated: 0,
        memoryAllocated: 0,
        pods: [],
        laneIndex: 0,
        labels: { 'node-role.kubernetes.io/worker': '', 'topology.kubernetes.io/zone': 'lane-1' },
        turretAngle: 0,
        ammoCount: 0,
      },
      {
        name: 'worker-2',
        role: 'worker',
        status: 'Ready',
        health: 100,
        cpuCapacity: 4,
        memoryCapacity: 8192, // 8Gi
        cpuAllocated: 0,
        memoryAllocated: 0,
        pods: [],
        laneIndex: 1,
        labels: { 'node-role.kubernetes.io/worker': '', 'topology.kubernetes.io/zone': 'lane-2' },
        turretAngle: 0,
        ammoCount: 0,
      },
      {
        name: 'worker-3',
        role: 'worker',
        status: 'Ready',
        health: 100,
        cpuCapacity: 2,
        memoryCapacity: 2048, // 2Gi
        cpuAllocated: 0,
        memoryAllocated: 0,
        pods: [],
        laneIndex: 2,
        labels: { 'node-role.kubernetes.io/worker': '', 'topology.kubernetes.io/zone': 'lane-3' },
        turretAngle: 0,
        ammoCount: 0,
      },
    ],
    requests: [
      {
        id: 'req-001',
        customerName: 'Sarah Jenkins',
        customerRole: 'Cluster Architect',
        characterType: 'normal',
        title: 'Inspect Cluster Workers',
        description: 'Welcome to the Bastion terminal! First, inspect the cluster to verify our worker nodes are Ready.',
        requirements: {
          type: 'inspect-nodes',
        },
        lane: 0,
        slaTimeSeconds: 90,
        rewardPoints: 100,
        hints: [
          'You need to list the nodes in the Kubernetes cluster.',
          "The 'kubectl get' command is used to list Kubernetes resources.",
          "Add the resource type 'nodes' or 'node' to the command.",
          'Execute: kubectl get nodes',
        ],
        learningNote: 'The cluster has 3 worker nodes (worker-1, worker-2, worker-3) in Ready state.',
      },
      {
        id: 'req-002',
        customerName: 'Mike Chen',
        customerRole: 'Frontend Lead',
        characterType: 'normal',
        title: 'Deploy First NGINX Workload',
        description: 'Customer requests a web frontend! Create an nginx pod named web-01.',
        requirements: {
          type: 'create-pod',
          podName: 'web-01',
          image: 'nginx',
        },
        lane: 1,
        slaTimeSeconds: 65,
        rewardPoints: 150,
        hints: [
          'You need to create a simple Pod workload.',
          "The 'kubectl run' command creates and runs a particular image in a Pod.",
          'Provide the pod name (web-01) and container image (--image=nginx).',
          'Execute: kubectl run web-01 --image=nginx',
        ],
        learningNote: 'When web-01 reached Running status, the assigned worker node cannon loaded ammunition and satisfied the customer request!',
      },
      {
        id: 'req-003',
        customerName: 'Elena Rostova',
        customerRole: 'SRE Specialist',
        characterType: 'normal',
        title: 'Discover Pod Placement',
        description: 'Find out which worker node the Kubernetes scheduler selected for web-01.',
        requirements: {
          type: 'inspect-pods-wide',
        },
        lane: 1,
        slaTimeSeconds: 70,
        rewardPoints: 120,
        hints: [
          'Regular kubectl get pods only shows basic status without the node column.',
          "Use the '-o wide' flag to display extended columns including NODE and IP.",
          'Combine kubectl get pods with the wide output format option.',
          'Execute: kubectl get pods -o wide',
        ],
        learningNote: "The '-o wide' flag reveals the NODE column. The Kubernetes scheduler placed web-01 based on capacity!",
      },
      {
        id: 'req-004',
        customerName: 'Devon Vance',
        customerRole: 'Data Engineer',
        characterType: 'urgent',
        title: 'Deploy Redis Cache Pod',
        description: 'Customer needs a fast caching layer! Create a pod named cache-01 using redis.',
        requirements: {
          type: 'create-pod',
          podName: 'cache-01',
          image: 'redis',
        },
        lane: 0,
        slaTimeSeconds: 50,
        rewardPoints: 180,
        hints: [
          'Deploy a new Pod object using the redis image.',
          "Use 'kubectl run' with the name cache-01.",
          'Specify the image flag: --image=redis.',
          'Execute: kubectl run cache-01 --image=redis',
        ],
        learningNote: 'Kubelet pulled the redis container image via CRI-O and transitioned cache-01 to Running.',
      },
      {
        id: 'req-005',
        customerName: 'Priya Patel',
        customerRole: 'API Developer',
        characterType: 'normal',
        title: 'Deploy Backend API Pod',
        description: 'Customer requests a backend service. Deploy a pod named api-01 using nginx.',
        requirements: {
          type: 'create-pod',
          podName: 'api-01',
          image: 'nginx',
        },
        lane: 2,
        slaTimeSeconds: 55,
        rewardPoints: 150,
        hints: [
          'Create another Pod named api-01.',
          'Remember the syntax: kubectl run <name> --image=<image>',
          'Target pod name is api-01 and image is nginx.',
          'Execute: kubectl run api-01 --image=nginx',
        ],
        learningNote: 'Multiple pods can run across different worker nodes simultaneously.',
      },
      {
        id: 'req-006',
        customerName: 'Marcus Wright',
        customerRole: 'Platform Engineer',
        characterType: 'normal',
        title: 'Inspect Worker-2 Capacity',
        description: 'Worker-2 is taking several pods. Check its allocated resources and events.',
        requirements: {
          type: 'describe-node',
          nodeName: 'worker-2',
        },
        lane: 1,
        slaTimeSeconds: 65,
        rewardPoints: 140,
        hints: [
          "The 'describe' command shows detailed resource allocations and events for an object.",
          "Specify the resource type 'node' and the target name 'worker-2'.",
          'Syntax: kubectl describe node <node-name>',
          'Execute: kubectl describe node worker-2',
        ],
        learningNote: 'kubectl describe node shows Capacity vs Allocatable CPU/RAM and non-terminated pods running on that machine.',
      },
      {
        id: 'req-007',
        customerName: 'Klaus Mueller',
        customerRole: 'ML Infrastructure',
        characterType: 'cpu-burner',
        title: 'Deploy Compute Workload (500m CPU)',
        description: 'Compute workload approaching! Create pod compute-01 using nginx with 500m CPU request.',
        requirements: {
          type: 'create-pod',
          podName: 'compute-01',
          image: 'nginx',
          minCpu: 0.5,
        },
        lane: 0,
        slaTimeSeconds: 50,
        rewardPoints: 220,
        hints: [
          'You need to specify resource requests during pod creation.',
          "Add the '--requests=cpu=500m' flag to kubectl run.",
          'Example: kubectl run compute-01 --image=nginx --requests=cpu=500m',
          'Execute: kubectl run compute-01 --image=nginx --requests=cpu=500m',
        ],
        learningNote: 'Kubernetes tracks CPU requests in millicores (500m = 0.5 cores) to prevent node CPU overcommitment.',
      },
      {
        id: 'req-008',
        customerName: 'Ananya Roy',
        customerRole: 'Database Administrator',
        characterType: 'memory-hog',
        title: 'Deploy Memory Cache (1024Mi RAM)',
        description: 'High-RAM workload incoming! Create pod db-01 using redis with 1024Mi memory request.',
        requirements: {
          type: 'create-pod',
          podName: 'db-01',
          image: 'redis',
          minMem: 1024,
        },
        lane: 2,
        slaTimeSeconds: 50,
        rewardPoints: 250,
        hints: [
          'You need to specify a memory resource request.',
          "Add the '--requests=memory=1024Mi' flag to kubectl run.",
          'Example: kubectl run db-01 --image=redis --requests=memory=1024Mi',
          'Execute: kubectl run db-01 --image=redis --requests=memory=1024Mi',
        ],
        learningNote: 'Memory requests guarantee RAM allocation on the selected worker node.',
      },
      {
        id: 'req-009',
        customerName: 'VP of Engineering',
        customerRole: 'Executive Incident Commander',
        characterType: 'escalation',
        title: 'MINI-BOSS: Enterprise Gateway Workload',
        description: 'High-priority production gateway! Deploy gateway-01 using nginx with cpu=1000m,memory=2048Mi!',
        requirements: {
          type: 'create-pod',
          podName: 'gateway-01',
          image: 'nginx',
          minCpu: 1.0,
          minMem: 2048,
        },
        lane: 1,
        slaTimeSeconds: 45,
        rewardPoints: 400,
        hints: [
          'This heavy workload requires both CPU and memory flags combined.',
          "Specify multiple requests separated by comma: '--requests=cpu=1000m,memory=2048Mi'",
          'Only worker nodes with sufficient remaining capacity will be eligible.',
          'Execute: kubectl run gateway-01 --image=nginx --requests=cpu=1000m,memory=2048Mi',
        ],
        learningNote: 'The Kube-Scheduler evaluated all 3 nodes, filtered out nodes with insufficient remaining RAM/CPU, and placed gateway-01 on worker-2!',
      },
    ],
    learningOutcomes: [
      'Worker nodes are the computational powerhouses that execute containerized applications.',
      'Pods are the smallest deployable objects in Kubernetes and encapsulate one or more containers.',
      'The Kube-Scheduler automatically assigns pending pods to eligible worker nodes using filtering and scoring.',
      '"kubectl get nodes" and "kubectl get pods -o wide" provide essential visibility into cluster topology and workload distribution.',
      '"kubectl describe node" displays allocatable vs requested CPU and Memory resources.',
      'Resource requests (CPU/Memory) ensure workloads receive dedicated capacity and prevent node overload.',
    ],
  },
];

export const allChapters: ChapterConfig[] = [
  {
    id: 1,
    title: 'Chapter 1: Nodes & Scheduling',
    description: 'Learn cluster anatomy, worker cannons, pod placement, and kube-scheduler scoring.',
    badge: 'NODES',
    unlocked: true,
    levels: chapter01Levels,
  },
  {
    id: 2,
    title: 'Chapter 2: Pods & Lifecycle',
    description: 'Dive deep into Pod states: Pending, ContainerCreating, Running, CrashLoopBackOff, and ImagePullBackOff.',
    badge: 'PODS',
    unlocked: false,
    levels: [],
  },
  {
    id: 3,
    title: 'Chapter 3: Deployments & ReplicaSets',
    description: 'Master self-healing workloads, rolling updates, rollbacks, and replica scaling.',
    badge: 'DEPLOY',
    unlocked: false,
    levels: [],
  },
  {
    id: 4,
    title: 'Chapter 4: Services & Networking',
    description: 'ClusterIP, NodePort, LoadBalancer, and Kubernetes Ingress Controllers.',
    badge: 'NETWORKING',
    unlocked: false,
    levels: [],
  },
  {
    id: 5,
    title: 'Chapter 5: Troubleshooting & Boss Battles',
    description: 'Node NotReady emergencies, CPU throttling, and etcd split-brain defense!',
    badge: 'INCIDENTS',
    unlocked: false,
    levels: [],
  },
];
